const mongoose = require("mongoose");

// A student's attempt at a quiz generated by the app's AI from a scanned note.
// Unlike McqAttempt, these quizzes are ad-hoc (not tied to a Course/CourseContent),
// so we store the full question snapshot alongside the score.
const aiQuizQuestionSchema = new mongoose.Schema(
  {
    question:     { type: String, required: true },
    options:      [{ type: String }],
    correctIndex: { type: Number, required: true },
    chosenIndex:  { type: Number, default: -1 }, // -1 = left unanswered
    explanation:  { type: String, default: "" },
  },
  { _id: false },
);

const aiQuizAttemptSchema = new mongoose.Schema({
  user_id:   { type: mongoose.Schema.Types.ObjectId, ref: "User", required: true },
  // Note context this quiz was generated from.
  topic:     { type: String, default: "" },
  title:     { type: String, default: "" },
  questions: [aiQuizQuestionSchema],
  score:     { type: Number, required: true },
  total:     { type: Number, required: true },
  // score / total as a 0–100 percentage, for easy averaging/leaderboards.
  percentage: { type: Number, required: true },
  created_at: { type: Date, default: Date.now },
});

module.exports = mongoose.model("AiQuizAttempt", aiQuizAttemptSchema);
