const mongoose = require("mongoose");

// A study plan generated by the AI for a student. Saved automatically whenever
// POST /api/study-plan/generate succeeds, so the student can revisit past plans.
// The `parts` payload mirrors the structured plan the AI returns (title,
// subtitle, formula, theory, explanation, examples, achieve) — kept as Mixed so
// the schema doesn't have to track every field the prompt evolves to produce.
const studyPlanSchema = new mongoose.Schema(
  {
    user_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "User",
      required: true,
      index: true,
    },
    // Context the plan was built for.
    className: { type: String, default: "" },
    subject: { type: String, default: "" },
    topic: { type: String, default: "" },
    subTopic: { type: String, default: "" },
    focus: { type: String, default: "" },
    language: { type: String, default: "en" },
    // AI output.
    overview: { type: String, default: "" },
    parts: { type: mongoose.Schema.Types.Mixed, default: [] },
    created_at: { type: Date, default: Date.now },
  },
);

module.exports = mongoose.model("StudyPlan", studyPlanSchema);
